---
name: Math-Random-ISAAC
version: 1.000006
author:
  - 'Jonathan Yu <frequency@cpan.org>'
abstract: Perl interface to the ISAAC PRNG Algorithm
license: unrestricted
requires:
  Carp: 1.04
  Test::More: 0.62
  integer: 0
  perl: 5.006
  strict: 0
  version: 0.76
  warnings: 0
build_requires:
  Test::NoWarnings: 0.084
recommends:
  Math::Random::ISAAC::XS: 0
dynamic_config: 0
provides:
  Math::Random::ISAAC:
    file: lib/Math/Random/ISAAC.pm
    version: 1.000006
  Math::Random::ISAAC::PP:
    file: lib/Math/Random/ISAAC/PP.pm
    version: 1.000005
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
resources:
  Ratings: http://cpanratings.perl.org/d/Math-Random-ISAAC
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Math-Random-ISAAC
  license: http://edwardsamuels.com/copyright/beyond/articles/public.html
  repository: http://svn.ali.as/cpan/trunk/Math-Random-ISAAC
